version: '3.5'
services:
  node_app:
    container_name: node_app
    build:
      dockerfile: Dockerfile
    working_dir: /home/www/tinyurl
    environment:
      - NODE_ENV=development
    expose:
      - 8000
    ports:
      - 8000:8000
    volumes:
      - ./tinyurl/lib:/home/www/tinyurl/lib
      - ./tinyurl/pages:/home/www/tinyurl/pages
      - ./tinyurl/public:/home/www/tinyurl/public
      - ./tinyurl/next.config.js:/home/www/tinyurl/next.config.js
      - ./tinyurl/.env.local:/home/www/tinyurl/.env.local
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
