version: '3.5'
services:
  node_app:
    container_name: node_app
    build:
      dockerfile: Dockerfile
    working_dir: /home/www/tinyurl
    environment:
      - NODE_ENV=development
    expose:
      - 8000
    ports:
      - 8000:8000
    volumes:
      - ./tinyurl:/home/www/tinyurl
      - /home/www/tinyurl/.next/
      - /home/www/tinyurl/node_modules/
  mongo:
    image: mongo
    container_name: mongo_db
    restart: always
    expose:
      - 27016
    ports:
      - 27016:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
